image: docker

stages:
  - lint

.lint-job: &lint_job
  image: python:3.10-slim
  stage: lint
  interruptible: true
  cache:
    - key:
        files:
          - pdm.lock
      paths:
        - .venv
        - .cache/pip
  only:
    changes:
      - "**/*.py"
      - pdm.lock
      - pyproject.toml

  before_script:
    - pip install pdm
    - pdm install
  variables:
    GIT_STRATEGY: clone
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

mypy:
  <<: *lint_job
  script:
    - pdm run mypy .

black:
  <<: *lint_job
  script:
    - pdm run black . --check

isort:
  <<: *lint_job
  script:
    - pdm run isort . --check

flake8:
  <<: *lint_job
  script:
    - pdm run flake8

bandit:
  <<: *lint_job
  script:
    - pdm run bandit schema_filters -r

pytest:
  <<: *lint_job
  script:
    - pdm run coverage run
    - pdm run coverage report -m
    - pdm run coverage xml
  coverage: "/^TOTAL.*\\s(\\d*)/"
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
